name: First

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  console-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Console Log
        run: echo "First action"