name: Second

on:
  workflow_run:
    workflows: [First]
    types: [completed]

jobs:
  console-log:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Console Log
        run: echo "Second action"